console.log("from external script:\n");
var firstName,age;
var schname,isSmart;
firstName = "Sarvadnya";
age = 5;
schName = "Kennedy";
isSmart = true;
console.log(firstName + " " + "AND " + " " + age + " " + schName + " "+ isSmart);
var frst,secnd,thrd;
frst=12;
secnd=21;
thrd=frst > secnd;
console.log(frst > secnd);
console.log(typeof thrd );
console.log(typeof age);
console.log(typeof "Sarvadnya is GOD's gift");
console.log("from external script:\n");
var firstName,age;
var schname,isSmart;
firstName = "Sarvadnya";
age = 5;
schName = "Kennedy";
isSmart = true;
console.log(firstName + " " + "AND " + " " + age + " " + schName + " "+ isSmart);
var frst,secnd,thrd;
frst=12;
secnd=21;
thrd=frst > secnd;
console.log(frst > secnd);
console.log(typeof thrd );
console.log(typeof age);
console.log(typeof "Sarvadnya is GOD's gift");
